language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

  license:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - -.+

before_install:
- yes | sdkmanager "platforms;android-28"

before_script:
- sed -i "s/app_icon/app_icon_devel/g" app/src/main/AndroidManifest.xml
- sed -i "s/com.danhasting.radar/com.danhasting.radar.devel/g" app/build.gradle
- sed -i "s/versionName \"\([0-9\.]\+\)\"/versionName \"\1~git:${TRAVIS_COMMIT:0:7}\"/g" app/build.gradle

before_deploy:
- mkdir app/build/outputs/apk/debug/$TRAVIS_BRANCH/
- mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/$TRAVIS_BRANCH/com.danhasting.radar.devel.apk

deploy:
  provider: s3
  access_key_id:
    secure: WPM4D/l3z0t6Z+ICMRC0xckNpqjq8QYpeqdjwETi5rZUqfM6ZDCpqv2ougW6V2V72O6NOF7GXGGpn27xWhgHOPseShzKOvZS/ggkp6Amti9pBid5ez6nr7Nr63347NelulFbYa0Y3ClyGoxecB+bA0UaynrDp2A/LcMlR4R4qN2WS2MJjzroZKFvZaS8Hk3gqjlpBOhkwEFZDI5u17rmAmtTabGYQw+UGUI6D2AdfRyPhCXwLHOX6gQx6gN8lMH6iOPp5XYsnQ8wX1ezMufjAN4Gp9faCwlPIJeDjMywxpV4o4GZRWaqfht4u7uqkLI7uZwRqO8XiJxCZw5OXjsJTKr6rC39VaEJAavkcxNw0ETQz8j3N3jYYi89ydae4+NGw3Ufg+kz4u5THOOERegvSGLJEXeiOyQaEDpv0WP7KRf+v7MpcK+Y7sQ/oIqKMNB98WHNyQtFbnalqGXFhJCel12IbIKiqZNEus0d31Mt/4mp4w5UyHQXP3MGbl607xs1T5oVnD8Vs5oUFBMFoKy7UNN1UAZsqKYlNF48Lyuf/mxoRhTykBPEWqpm3rr4Nrhv8ZKp5KT0TVjYZlI3IqlI9iRIf5f/tKMWrTQ7sXPsP9p7RW6h9iJvmykiQ+5usFiypE+Q8Xa/hZDAiJYzQL3BfrmhkTDW6FPR3geFYyRbM2g=
  secret_access_key:
    secure: gQCJbNQhlMI+aBB08LPpm9Dy5wdQPbNmw0SK/ZSXtHBRYNh+YeDfdn4SY62B3gnsGxoDU5Alz+f7OI9ZMoh4V3QZNSUT9AV00IBk28EimsSKGuSKtbdyYVEDbvqLLBO+j9+sfDMyQ/BXQh1ZnNcpWTnNe9OBs+0fWhGeQ9Nq+TLXKBqemn+o/xpzlDUFWPG/9mzHjRU0Gxpq3arNppZR/2jRhCbn4d0mODpWQoeKJ20NL6inRmcaNmGjJru06254K6KjIp70c2/1rKAJASNQB3WLwZ6uHP2en3d4NDaR8CSMZnhhkQxSJQXCfdd1BlZiPQ5WNF1fdtafLz2VNqOvR3EFOBPxKHEii+YNtKkmkrH1JVbvGbszToXCBiYZ6ur3QfUURhPLP0KRUsP9el/KSalCOivQ4wQb9MhjmcInPfSabGqXmEV2po8bZ2S+4YRGWGbQnswHVY2EoPloB74w5f+kQKbZAlHbfUnmp72WzbzdJ72KvJKRfZKJYS3R5FbQg04mJ7sRrROolBoNDLXjGM/CyugHkhCuNK9Vk5vBpFH5I+38JlTuNzkuLgi76i2NUTj8LyfL5uK89tBEZsKrAlv/vNP0rgosI50iwVtmaVhAawlmjhSQQ3hwrkdPgW92TlvxaD2bn8JB6LZ50r6T3TJfcx65xM1HDetRyyY4ALU=
  bucket: dh4
  skip_cleanup: true
  local_dir: app/build/outputs/apk/debug
  upload-dir: weather_radar
  on:
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST = false"
